server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/infinitychat'
    username: 'postgres'
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # disable logging of sql statements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
